export const FECTH_PRODUCT = "FECTH_PRODUCTS";
export const ADD_PRODUDCT = "ADD_PRODUDCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT="EDIT_PRODUCT";